config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # resources :restaurants, only: %i[index show new create]
  get 'restaurants', to: 'restaurants#index', as: :restaurants
  get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant
  post 'restaurants', to: 'restaurants#create'
  get 'restaurants/:id/reviews/new', to: 'reviews#new', as: :new_review
  post 'restaurants/:id/reviews', to: 'reviews#create', as: :create_review
  get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

  # Defines the root path route ('/')
  # root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build(review_params)

    if @review.save
      redirect_to @restaurant, notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Restaurants', restaurants_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Create Restaurant', new_restaurant_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<table class="table">
  <!-- Table header -->
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant_path(restaurant) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/new.html.erb
<h1>Create Restaurant</h1>
<%= render 'shared/form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<!-- app/views/restaurants/show.html.erb -->

<h1><%= @restaurant.name %></h1>
<!-- Display other details of the restaurant -->
<h2><%= @restaurant.category %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<%= link_to 'Wriite a Review', new_review_path(restaurant_id: @restaurant.id), class: 'btn btn-primary' %>

app/views/reviews/new.html.erb
<h1>Review Restaurant</h1>
<%= render 'shared/form', review: @review %>

app/views/shared/_form.html.erb
<%= simple_form_for(@restaurant) do |form| %>
  <%= form.input :name, label: 'Name', input_html: { class: 'form-control' } %>

  <%= form.input :category, label: 'Category', input_html: { class: 'form-control' } %>

  <%= form.input :address, label: 'Address', input_html: { class: 'form-control' } %>

  <%= form.input :phone_number, label: 'Phone Number', input_html: { class: 'form-control' } %>

  <div class="actions">
    <%= form.button :submit, 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

<%= simple_form_for([@restaurant, @review], url: create_review_path(@restaurant)) do |form| %>
  <%= form.input :rating, label: 'Rating (1-5)', collection: 1..5, include_blank: false %>
  <%= form.input :content, label: 'Review content', as: :text, input_html: { rows: 4 } %>

  <!-- Review Form Submit Button -->
  <div class="actions">
    <%= form.button :submit, 'Submit Review', class: 'btn btn-primary' %>
  </div>
<% end %>